CREATE TABLE `practice_memory` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`content` text NOT NULL,
	`memory_type` text NOT NULL,
	`scope` text NOT NULL,
	`owner_email` text NOT NULL,
	`owner_role` text NOT NULL,
	`status` text NOT NULL,
	`status_before_delete` text,
	`source` text NOT NULL,
	`tags` text DEFAULT '' NOT NULL,
	`version` text DEFAULT '1' NOT NULL,
	`use_count` text DEFAULT '0' NOT NULL,
	`helpful_count` text DEFAULT '0' NOT NULL,
	`review_count` text DEFAULT '0' NOT NULL,
	`last_used_at` text,
	`approved_at` text,
	`approved_by` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`deleted_at` text,
	`deleted_by` text,
	`delete_reason` text
);
