"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { hubFetch, label } from "@/app/lib/client-api";

type Row=Record<string,string|null>;
type SafetyData={alerts:Row[];shifts:Row[];schedules:Row[];profiles:Row[];canClose:boolean};

export function DirectorSafety({mode}:{mode:"alerts"|"workload"}){
  const [data,setData]=useState<SafetyData>({alerts:[],shifts:[],schedules:[],profiles:[],canClose:false}),[actions,setActions]=useState<Record<string,string>>({}),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{try{setData(await hubFetch("/api/safety"));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load safety controls")}},[]);
  useEffect(()=>{const initial=setTimeout(()=>void load(),0);const timer=setInterval(()=>void load(),7000);return()=>{clearTimeout(initial);clearInterval(timer)}},[load]);
  async function alertAction(id:string,action:string){try{await hubFetch("/api/safety",{method:"PATCH",body:JSON.stringify({id,action,actionTaken:actions[id]})});setNotice(action==="signoff_close"?"Supervisor sign-off completed and the alert was closed.":"Action recorded. Supervisor sign-off is still required before closure.");await load()}catch(e){setError(e instanceof Error?e.message:"Alert update failed")}}
  async function limits(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await hubFetch("/api/safety",{method:"POST",body:JSON.stringify({action:"set_limits",staffEmail:f.get("staffEmail"),maxDailyHours:f.get("maxDailyHours"),maxDailySessions:f.get("maxDailySessions"),maxHighSupportSessions:f.get("maxHighSupportSessions"),lunchAfterMinutes:f.get("lunchAfterMinutes")})});setNotice("Workload limits approved and saved.");await load()}catch(e){setError(e instanceof Error?e.message:"Limits not saved")}}
  async function approve(email:string){try{await hubFetch("/api/safety",{method:"POST",body:JSON.stringify({action:"approve_profile",staffEmail:email})});setNotice("Worker preference reviewed and approved.");await load()}catch(e){setError(e instanceof Error?e.message:"Approval failed")}}
  const scheduleBy=(email:string)=>data.schedules.filter(item=>item.staff_email===email),shiftBy=(email:string)=>data.shifts.find(item=>item.staff_email===email);

  if(mode==="alerts")return <>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success" onClick={()=>setNotice("")}>{notice}</div>}<section className="director-hero"><div><span className="eyebrow">Controlled escalation and closure</span><h2>Safety Alerts</h2><p>Acknowledge → record the action actually completed → authorised supervisor sign-off → close. Sending a message alone never deactivates the alert.</p></div><div className="connection-flow"><span>Detect</span><b>→</b><span>Act</span><b>→</b><span>Sign off</span></div></section><div className="alert-stack director-alerts">{data.alerts.length?data.alerts.map(alert=><article className={`safety-alert ${alert.severity}`} key={alert.id||""}><div><span className={`pill ${alert.severity}`}>{label(alert.alert_type||"")}</span><b>{alert.staff_email}</b><span>{label(alert.status||"")}</span></div><p>{alert.detail}</p>{alert.action_taken&&<p className="recorded-action"><b>Recorded action:</b> {alert.action_taken}</p>}{!alert.actioned_at&&<><textarea value={actions[alert.id||""]||""} onChange={e=>setActions({...actions,[alert.id||""]:e.target.value})} placeholder="Record the action that was actually completed…"/><button onClick={()=>alertAction(alert.id||"","record_action")}>Record completed action</button></>}{alert.actioned_at&&!alert.supervisor_signoff_at&&data.canClose&&<button className="gold-button" onClick={()=>alertAction(alert.id||"","signoff_close")}>Supervisor sign-off and close</button>}<small>{alert.escalated_at?`Escalated ${new Date(alert.escalated_at).toLocaleString("en-AU")}`:"Active human review"} · Closure is permission-controlled and audited.</small></article>):<div className="empty-state"><span>✓</span><p>No open safety alerts.</p></div>}</div></>;

  return <>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success" onClick={()=>setNotice("")}>{notice}</div>}<section className="director-hero"><div><span className="eyebrow">Psychosocial workload controls</span><h2>Workload Protection</h2><p>Review hours, lunch timing, session load, high-support work and adult/child transitions with each worker. These are planning signals, not performance or clinical-risk scores.</p></div></section><div className="workload-cards">{data.profiles.map(profile=>{const schedule=scheduleBy(profile.email||""),shift=shiftBy(profile.email||""),high=schedule.filter(item=>item.support_intensity==="high").length;return <article key={profile.email||""}><div className="workload-head"><div><b>{profile.email}</b><small>{label(profile.age_pattern||"")}</small></div><span className={profile.preferences_confirmed_at?"approved":"pending"}>{profile.preferences_confirmed_at?"Approved":"Review needed"}</span></div><div className="workload-metrics"><span><b>{schedule.length}/{profile.max_daily_sessions}</b>sessions</span><span><b>{high}/{profile.max_high_support_sessions}</b>high-support</span><span><b>{profile.transition_buffer_minutes}m</b>age buffer</span><span><b>{profile.max_daily_hours}h</b>hours limit</span></div><p>Lunch due after {Math.round(Number(profile.lunch_after_minutes||240)/60*10)/10} hours. Current state: {shift?label(shift.break_state||"working"):"No active shift"}.</p>{!profile.preferences_confirmed_at&&<button onClick={()=>approve(profile.email||"")}>Approve worker preference</button>}</article>})}</div><section className="director-panel limit-panel"><div className="panel-head"><h2>Set approved workload limits</h2><span>Consult the worker and review after incidents or change</span></div><form className="limit-form" onSubmit={limits}><label>Staff email<select name="staffEmail" required><option value="">Choose…</option>{data.profiles.map(profile=><option key={profile.email||""} value={profile.email||""}>{profile.email}</option>)}</select></label><label>Daily hours<input name="maxDailyHours" type="number" min="1" max="16" defaultValue="8" required/></label><label>Sessions<input name="maxDailySessions" type="number" min="1" max="14" defaultValue="6" required/></label><label>High-support<input name="maxHighSupportSessions" type="number" min="1" max="10" defaultValue="2" required/></label><label>Lunch due (min)<input name="lunchAfterMinutes" type="number" min="60" max="480" defaultValue="240" required/></label><button className="gold-button">Approve and save</button></form></section></>;
}
