"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { hubFetch, label } from "@/app/lib/client-api";

type Row=Record<string,string|null>;
type Data={items:Row[];canGovern:boolean;actor:{email:string;role:string;displayName:string;demo:boolean};stats:{active:number;proposed:number;review:number;deleted:number}};
type Audience="director"|"staff"|"reception";

export function MemoryCentre({audience}:{audience:Audience}){
  const [data,setData]=useState<Data>({items:[],canGovern:false,actor:{email:"",role:"",displayName:"",demo:false},stats:{active:0,proposed:0,review:0,deleted:0}}),[mode,setMode]=useState<"library"|"learning"|"deleted">("library"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Row|null>(null),[target,setTarget]=useState<Row|null>(null),[reason,setReason]=useState(""),[confirmTitle,setConfirmTitle]=useState("");
  const load=useCallback(async()=>{try{setData(await hubFetch(`/api/memory${audience==="director"?"?deleted=1":""}`,{},audience==="reception"?"reception":"psychologist"));setError("")}catch(e){setError(e instanceof Error?e.message:"Memory could not be loaded")}finally{setLoading(false)}},[audience]);
  useEffect(()=>{const initial=setTimeout(()=>void load(),0);const timer=setInterval(()=>void load(),12000);return()=>{clearTimeout(initial);clearInterval(timer)}},[load]);
  const items=useMemo(()=>data.items.filter(item=>mode==="deleted"?Boolean(item.deleted_at):!item.deleted_at&&(mode==="learning"?(item.status==="proposed"||Number(item.review_count||0)>0):item.status!=="proposed")),[data.items,mode]);
  const scope=audience==="director"?"all_staff":audience==="reception"?"reception":"psychology";

  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{if(editing){await hubFetch("/api/memory",{method:"PATCH",body:JSON.stringify({id:editing.id,action:"update",title:f.get("title"),content:f.get("content"),tags:f.get("tags")})},audience==="reception"?"reception":"psychologist")}else{await hubFetch("/api/memory",{method:"POST",body:JSON.stringify({title:f.get("title"),content:f.get("content"),memoryType:f.get("memoryType"),scope:f.get("scope"),tags:f.get("tags")})},audience==="reception"?"reception":"psychologist")}event.currentTarget.reset();setEditing(null);setNotice(editing?"Memory revised. The version history number was updated.":data.canGovern?"Practice memory approved and saved.":"Memory saved privately or sent to Irene for approval.");await load()}catch(e){setError(e instanceof Error?e.message:"Memory not saved")}}
  async function act(id:string,action:string,extra:Record<string,unknown>={}){try{await hubFetch("/api/memory",{method:"PATCH",body:JSON.stringify({id,action,...extra})},audience==="reception"?"reception":"psychologist");setNotice(action==="approve"?"Learning approved as practice memory.":action==="restore"?"Memory restored.":action==="purge"?"Archived memory permanently purged; its audit event remains.":"Memory updated.");setTarget(null);setReason("");setConfirmTitle("");await load()}catch(e){setError(e instanceof Error?e.message:"Memory action failed")}}
  function editable(item:Row){return data.canGovern||item.owner_email===data.actor.email&&(item.scope==="private"||item.status==="proposed"||item.status_before_delete==="proposed")}

  if(loading)return <div className="memory-loading">Opening practice memory…</div>;
  return <section className={`memory-centre ${audience}`}>
    {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success" onClick={()=>setNotice("")}>{notice}</div>}
    <header className="memory-hero"><div><span className="eyebrow">Remember • learn • review • delete safely</span><h2>{audience==="director"?"Practice Memory & Learning":audience==="reception"?"Reception Memory":"My Memory & Learning"}</h2><p>Operational knowledge only. No client names, therapy notes, diagnosis, clinical-risk scoring or autonomous learning.</p></div><div className="memory-loop"><span>Remember</span><b>→</b><span>Feedback</span><b>→</b><span>Irene approves</span></div></header>
    <div className="memory-stats"><button onClick={()=>setMode("library")} className={mode==="library"?"active":""}><b>{data.stats.active}</b><span>Current memory</span></button><button onClick={()=>setMode("learning")} className={mode==="learning"?"active":""}><b>{data.stats.proposed}</b><span>Learning proposals</span></button><button onClick={()=>setMode("learning")}><b>{data.stats.review}</b><span>Review requests</span></button>{data.canGovern&&<button onClick={()=>setMode("deleted")} className={mode==="deleted"?"active":""}><b>{data.stats.deleted}</b><span>Archived / deleted</span></button>}</div>
    <div className="memory-layout"><section className="memory-list"><div className="memory-tabs"><button className={mode==="library"?"active":""} onClick={()=>setMode("library")}>Memory library</button><button className={mode==="learning"?"active":""} onClick={()=>setMode("learning")}>Learning review</button>{data.canGovern&&<button className={mode==="deleted"?"active":""} onClick={()=>setMode("deleted")}>Deletion centre</button>}</div>
      {items.length?<div className="memory-cards">{items.map(item=><article key={item.id||""} className={`memory-card ${item.status}`}><div className="memory-card-head"><div><span className="pill">{label(item.memory_type||"")}</span><span className="scope-chip">{label(item.scope||"")}</span></div><b>{label(item.status||"")}</b></div><h3>{item.title}</h3><p>{item.content}</p><div className="memory-meta"><span>Owner: {item.owner_email}</span><span>v{item.version}</span><span>Used {item.use_count||0}</span><span>Helpful {item.helpful_count||0}</span><span>Review {item.review_count||0}</span></div>{item.tags&&<small>Tags: {item.tags}</small>}{item.deleted_at&&<div className="delete-note"><b>Archived:</b> {item.delete_reason} · {new Date(item.deleted_at).toLocaleString("en-AU")}</div>}<div className="memory-actions">{!item.deleted_at&&<><button onClick={()=>act(item.id||"","feedback",{feedback:"used"})}>Used today</button><button onClick={()=>act(item.id||"","feedback",{feedback:"helpful"})}>Worked well</button><button onClick={()=>act(item.id||"","feedback",{feedback:"needs_review"})}>Needs review</button></>}{data.canGovern&&item.status==="proposed"&&!item.deleted_at&&<button className="approve" onClick={()=>act(item.id||"","approve")}>Irene approve</button>}{editable(item)&&!item.deleted_at&&<><button onClick={()=>{setEditing(item);window.scrollTo({top:0,behavior:"smooth"})}}>Revise</button><button className="archive" onClick={()=>setTarget(item)}>Archive</button></>}{item.deleted_at&&editable(item)&&<button onClick={()=>act(item.id||"","restore")}>Restore</button>}{item.deleted_at&&data.actor.role==="director"&&<button className="purge" onClick={()=>setTarget(item)}>Permanent purge</button>}</div></article>)}</div>:<div className="empty-state"><span>✓</span><p>{mode==="deleted"?"No archived memory.":mode==="learning"?"No learning is waiting for review.":"No memory is available in this role."}</p></div>}
    </section>
    {mode!=="deleted"&&<aside className="memory-form-panel"><h2>{editing?"Revise memory":data.canGovern?"Add approved memory":"Remember or propose learning"}</h2><p>{data.canGovern?"Irene can publish operational guidance to a role. Staff feedback never rewrites it automatically.":"Keep a private preference or propose a role lesson for Irene’s review."}</p><form className="stack-form" onSubmit={save}><label>Title<input name="title" required maxLength={120} defaultValue={editing?.title||""} key={`title-${editing?.id||"new"}`}/></label>{!editing&&<><label>Type<select name="memoryType"><option value="lesson">Lesson learned</option><option value="preference">Preference</option><option value="workflow">Workflow</option><option value="handover">Handover reminder</option>{data.canGovern&&<><option value="policy">Policy</option><option value="script">Approved script</option></>}</select></label><label>Visibility<select name="scope" defaultValue={scope}><option value="private">Private to me</option><option value={scope}>{label(scope)}</option>{data.canGovern&&<><option value="all_staff">All staff</option><option value="psychology">Psychology staff</option><option value="reception">Reception</option><option value="director">Director only</option></>}</select></label></>}<label>Operational memory<textarea name="content" required rows={7} maxLength={1400} defaultValue={editing?.content||""} key={`content-${editing?.id||"new"}`} placeholder="What should be remembered, why it helps, and when it applies. No client-identifying or clinical content."/></label><label>Tags<input name="tags" maxLength={180} defaultValue={editing?.tags||""} key={`tags-${editing?.id||"new"}`} placeholder="e.g. lunch, reception, handover"/></label><button className="gold-button">{editing?"Save new version":data.canGovern?"Approve and remember":"Save / send for approval"}</button>{editing&&<button type="button" className="cancel-button" onClick={()=>setEditing(null)}>Cancel revision</button>}</form></aside>}
    </div>
    {target&&<div className="memory-confirm"><section role="dialog" aria-modal="true" aria-labelledby="memoryConfirmTitle"><button className="close-confirm" aria-label="Close" onClick={()=>{setTarget(null);setReason("");setConfirmTitle("")}}>×</button><h2 id="memoryConfirmTitle">{target.deleted_at?"Permanent purge":"Archive memory"}</h2><p><b>{target.title}</b></p><p>{target.deleted_at?"This removes the memory record permanently. The purge audit event remains. This cannot be undone.":"Archiving hides the memory but keeps it recoverable in Irene’s Deletion Centre."}</p><label>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3}/></label>{target.deleted_at&&<label>Type the exact title<input value={confirmTitle} onChange={e=>setConfirmTitle(e.target.value)}/></label>}<div><button onClick={()=>setTarget(null)}>Cancel</button><button className={target.deleted_at?"purge":"archive"} onClick={()=>act(target.id||"",target.deleted_at?"purge":"archive",{reason,confirmTitle})}>{target.deleted_at?"Permanently purge":"Archive safely"}</button></div></section></div>}
  </section>
}
