"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { SafeGuide } from "@/app/components/safe-guide";
import { hubFetch, label } from "@/app/lib/client-api";
import { usePersistentView } from "@/app/lib/use-persistent-view";
import { MemoryCentre } from "@/app/components/memory-centre";

type Row=Record<string,string|null>;
type Actor={email:string;displayName:string;role:string;demo:boolean};
const allowed=["director","board","practice_manager","reception","clinical_lead"];

export function ReceptionBase(){
  const [actor,setActor]=useState<Actor|null>(null),[items,setItems]=useState<Row[]>([]),[scripts,setScripts]=useState<Row[]>([]),[messages,setMessages]=useState<Row[]>([]),[safety,setSafety]=useState<{alerts:Row[];shifts:Row[]}>({alerts:[],shifts:[]});
  const [view,setView]=usePersistentView("reception","queue");
  const [error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[outcomes,setOutcomes]=useState<Record<string,string>>({});

  const load=useCallback(async()=>{try{const [session,reception,messageData,safetyData]=await Promise.all([hubFetch("/api/session",{},"reception"),hubFetch("/api/reception",{},"reception"),hubFetch("/api/messages",{},"reception"),hubFetch("/api/safety",{},"reception")]);setActor(session.actor);setItems(reception.items||[]);setScripts(reception.scripts||[]);setMessages(messageData.messages||[]);setSafety(safetyData);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to connect")}finally{setLoading(false)}},[]);
  useEffect(()=>{const initial=setTimeout(()=>void load(),0);const timer=setInterval(()=>void load(),8000);return()=>{clearTimeout(initial);clearInterval(timer)}},[load]);

  async function addItem(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await hubFetch("/api/reception",{method:"POST",body:JSON.stringify({clientCode:f.get("clientCode"),itemType:f.get("itemType"),detail:f.get("detail"),priority:f.get("priority"),dueAt:f.get("dueAt")})},"reception");event.currentTarget.reset();setNotice("Coded reception item added.");await load()}catch(e){setError(e instanceof Error?e.message:"Item not added")}}
  async function updateItem(id:string,action:string){try{await hubFetch("/api/reception",{method:"PATCH",body:JSON.stringify({id,action,outcome:outcomes[id]||"Reception requested an authorised human owner."})},"reception");setNotice(action==="escalate"?"Escalated to Irene’s dashboard.":"Reception action recorded.");await load()}catch(e){setError(e instanceof Error?e.message:"Update failed")}}
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await hubFetch("/api/messages",{method:"POST",body:JSON.stringify({subject:f.get("subject"),body:f.get("body"),category:"reception",priority:f.get("priority")})},"reception");event.currentTarget.reset();setNotice("Message sent to Irene’s dashboard.");await load()}catch(e){setError(e instanceof Error?e.message:"Message failed")}}
  async function safetyAction(action:string,payload:Record<string,unknown>={}){try{await hubFetch("/api/safety",{method:"POST",body:JSON.stringify({action,...payload})},"reception");setNotice("Safety action recorded; authorised sign-off controls alert closure.");await load()}catch(e){setError(e instanceof Error?e.message:"Safety action failed")}}

  if(loading)return <div className="loading-screen">Opening the reception safety base…</div>;
  if(!actor)return <Access error={error}/>;
  if(!allowed.includes(actor.role))return <Access error="This account does not have reception access."/>;
  const open=items.filter(item=>item.status!=="completed").length,urgent=items.filter(item=>item.priority==="red"&&item.status!=="completed").length;

  return <main className="phone-app reception-app">
    <header className="mobile-top"><Link href="/" className="mini-brand"><img src="/demo/assets/icon-192.png" alt="Approved GENEVIEVE App emblem"/><span><b>GENEVIEVE</b><small>RECEPTION BASE</small></span></Link><button className="round-user">{actor.displayName.slice(0,2).toUpperCase()}</button></header>
    <div className="fiction-banner"><b>RESTRICTED OPERATIONAL VIEW</b><span>Coded references only. No clinical notes, diagnosis or risk judgement.</span></div>
    <section className="phone-content">{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success" onClick={()=>setNotice("")}>{notice}</div>}
      {view==="queue"&&<><div className="staff-welcome"><span>Reception safety and contact operations</span><h1>Reception Base</h1><p>Own the contact, use the approved words, and escalate to an authorised human.</p></div><div className="phone-stats"><button><b>{open}</b><span>Open reception items</span></button><button><b>{urgent}</b><span>Urgent human reviews</span></button><button onClick={()=>setView("safety")}><b>{safety.alerts.length}</b><span>My safety alerts</span></button></div><section className="mobile-card"><div className="card-title"><h2>My coded queue</h2><button onClick={()=>setView("new")}>Add</button></div>{items.length?<div className="feed">{items.map(item=><article key={item.id||""} className={`feed-item ${item.priority}`}><div><span className={`pill ${item.priority}`}>{label(item.item_type||"")}</span><time>{item.due_at?new Date(item.due_at).toLocaleString("en-AU"):"No due time"}</time></div><h3>Coded record {item.client_code}</h3><p>{item.detail}</p><small>Status: {label(item.status||"")}</small>{item.status!=="completed"&&<><textarea className="inline-outcome" aria-label="Operational outcome" value={outcomes[item.id||""]||""} onChange={e=>setOutcomes({...outcomes,[item.id||""]:e.target.value})} placeholder="Record attempt, transfer, owner or outcome…"/><div className="action-row"><button onClick={()=>updateItem(item.id||"","accept")}>Accept</button><button onClick={()=>updateItem(item.id||"","complete")}>Complete</button><button onClick={()=>updateItem(item.id||"","escalate")}>Escalate</button></div></>}</article>)}</div>:<Empty text="No reception items are waiting."/>}</section></>}
      {view==="scripts"&&<section className="mobile-card page-card"><div className="card-title"><h1>Approved scripts</h1><small>Read, do not diagnose</small></div><div className="script-list">{scripts.map(script=><article key={script.name||""}><b>{script.name}</b><p>{script.text}</p></article>)}</div><div className="emergency-note"><b>Immediate emergency</b><p>Follow the practice’s approved emergency procedure and call 000 when urgent emergency assistance is required. The program does not call automatically.</p></div></section>}
      {view==="messages"&&<section className="mobile-card page-card"><div className="card-title"><h1>Irene contact</h1><small>Private operational stream</small></div><form className="stack-form" onSubmit={send}><label>Priority<select name="priority"><option value="normal">Normal</option><option value="amber">Needs attention</option><option value="red">Urgent human review</option></select></label><label>Subject<input name="subject" required maxLength={120}/></label><label>Operational message<textarea name="body" required maxLength={1000} rows={4} placeholder="No clinical or identifying details."/></label><button className="gold-button">Send to Irene</button></form><div className="feed">{messages.slice(0,8).map(item=><article className="feed-item" key={item.id||""}><div><span className="pill">{item.sender_email===actor.email?"Sent":"Received"}</span><time>{new Date(item.created_at||"").toLocaleString("en-AU")}</time></div><h3>{item.subject}</h3><p>{item.body}</p></article>)}</div></section>}
      {view==="safety"&&<section className="mobile-card page-card"><div className="card-title"><h1>My Safety</h1><small>Reception is protected too</small></div><p className="lead">Track lunch, workload and support without displaying private details to coworkers.</p><div className="safety-action-grid">{safety.shifts.length===0?<button onClick={()=>safetyAction("start_shift")}><b>Start shift</b><span>Begin hours and lunch protection</span></button>:<><button onClick={()=>safetyAction("start_lunch")}><b>Start lunch</b><span>Record protected coverage</span></button><button onClick={()=>safetyAction("finish_lunch")}><b>Finish lunch</b><span>Return after the break</span></button></>}<button onClick={()=>safetyAction("check_in",{workloadCheck:"high",supportRequested:true})}><b>Request support</b><span>Escalate privately to Irene</span></button><button onClick={()=>setView("messages")}><b>Request coverage</b><span>Send an operational message</span></button></div><div className="alert-stack">{safety.alerts.map(alert=><article className={`safety-alert ${alert.severity}`} key={alert.id||""}><div><span className={`pill ${alert.severity}`}>{label(alert.alert_type||"")}</span><b>{label(alert.status||"")}</b></div><p>{alert.detail}</p><small>Only an authorised supervisor or safety person may close it after action is recorded.</small></article>)}</div></section>}
      {view==="new"&&<section className="mobile-card page-card"><div className="card-title"><h1>New coded item</h1><button onClick={()=>setView("queue")}>Cancel</button></div><form className="stack-form" onSubmit={addItem}><label>Coded reference<input name="clientCode" required maxLength={12} placeholder="e.g. F-R4"/></label><label>Type<select name="itemType"><option value="callback">Callback</option><option value="message">Message</option><option value="transfer">Transfer</option><option value="intake">Intake</option><option value="missed_contact">Missed contact</option></select></label><label>Priority<select name="priority"><option value="normal">Normal</option><option value="amber">Needs attention</option><option value="red">Urgent human review</option></select></label><label>Due<input name="dueAt" type="datetime-local"/></label><label>Minimum operational detail<textarea name="detail" required rows={4} maxLength={500}/></label><button className="gold-button">Add to reception queue</button></form></section>}
      {view==="memory"&&<MemoryCentre audience="reception"/>}
    </section>
    <nav className="mobile-nav"><button className={view==="queue"?"active":""} onClick={()=>setView("queue")}><span>☷</span>Queue</button><button className={view==="scripts"?"active":""} onClick={()=>setView("scripts")}><span>▤</span>Scripts</button><button className={view==="messages"?"active":""} onClick={()=>setView("messages")}><span>✉</span>Irene</button><button className={view==="safety"?"active":""} onClick={()=>setView("safety")}><span>♡</span>My Safety</button><button className={view==="memory"?"active":""} onClick={()=>setView("memory")}><span>◈</span>Memory</button></nav>
    <SafeGuide audience="reception" onNavigate={setView}/>
  </main>
}

function Empty({text}:{text:string}){return <div className="empty-state"><span>✓</span><p>{text}</p></div>}
function Access({error}:{error:string}){return <main className="access-screen"><img src="/demo/assets/icon-512.png" alt="GENEVIEVE App"/><h1>Reception Base</h1><p>{error}</p><a className="gold-button" href="/signin-with-chatgpt?return_to=/reception">Sign in with ChatGPT</a><small>Irene must authorise the exact reception or practice-management account.</small></main>}
