"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { hubFetch, label } from "@/app/lib/client-api";
import { SafeGuide } from "@/app/components/safe-guide";
import { DirectorSafety } from "@/app/components/director-safety";
import { usePersistentView } from "@/app/lib/use-persistent-view";
import { MemoryCentre } from "@/app/components/memory-centre";

type Actor={email:string;displayName:string;role:string;demo:boolean};
type Row=Record<string,string|null>;
const demoStaff=[
  {email:"avery@fictional.demo",display_name:"Dr Avery",role:"psychologist",status:"active"},
  {email:"sam@fictional.demo",display_name:"Sam",role:"provisional",status:"active"},
  {email:"mia@fictional.demo",display_name:"Mia",role:"reception",status:"active"},
];

export function IreneHub(){
  const [actor,setActor]=useState<Actor|null>(null),[staff,setStaff]=useState<Row[]>([]),[messages,setMessages]=useState<Row[]>([]),[assignments,setAssignments]=useState<Row[]>([]);
  const [view,setView]=usePersistentView("irene","overview");
  const [error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[replyTo,setReplyTo]=useState("");

  const load=useCallback(async()=>{try{const [session,s,m,a]=await Promise.all([hubFetch("/api/session"),hubFetch("/api/staff"),hubFetch("/api/messages"),hubFetch("/api/assignments")]);setActor(session.actor);setStaff(s.staff?.length?s.staff:demoStaff);setMessages(m.messages);setAssignments(a.assignments);setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to connect");}finally{setLoading(false)}},[]);
  useEffect(()=>{const initial=setTimeout(()=>void load(),0);const timer=setInterval(()=>void load(),7000);return()=>{clearTimeout(initial);clearInterval(timer)}},[load]);
  const openMessages=messages.filter(m=>m.sender_email!==actor?.email&&!m.acknowledged_at).length;
  const openTasks=assignments.filter(a=>!["completed","declined"].includes(a.status||"")).length;
  const activeStaff=staff.filter(s=>["active","invited"].includes(s.status||"")).length;
  const urgent=messages.filter(m=>m.priority==="red").length+assignments.filter(a=>a.priority==="red"&&a.status!=="completed").length;

  async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await hubFetch("/api/staff",{method:"POST",body:JSON.stringify({displayName:f.get("displayName"),email:f.get("email"),role:f.get("role")})});event.currentTarget.reset();setNotice("Staff access authorised. They must sign in using that exact ChatGPT email.");await load();}catch(e){setError(e instanceof Error?e.message:"Invite failed")}}
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await hubFetch("/api/messages",{method:"POST",body:JSON.stringify({recipientEmail:f.get("recipientEmail"),recipientRole:f.get("recipientRole"),subject:f.get("subject"),body:f.get("body"),category:f.get("category"),priority:f.get("priority")})});event.currentTarget.reset();setReplyTo("");setNotice("Message delivered to the staff member’s private app view.");await load();}catch(e){setError(e instanceof Error?e.message:"Message failed")}}
  async function assign(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await hubFetch("/api/assignments",{method:"POST",body:JSON.stringify({assignedToEmail:f.get("assignedToEmail"),title:f.get("title"),instructions:f.get("instructions"),category:f.get("category"),priority:f.get("priority"),dueAt:f.get("dueAt")})});event.currentTarget.reset();setNotice("Assignment sent and awaiting the staff member’s response.");await load();}catch(e){setError(e instanceof Error?e.message:"Assignment failed")}}
  async function access(email:string,status:string){try{await hubFetch("/api/staff",{method:"PATCH",body:JSON.stringify({email,status})});setNotice(`Access ${status}.`);await load();}catch(e){setError(e instanceof Error?e.message:"Access update failed")}}

  if(loading)return <div className="loading-screen">Opening Irene’s connected command centre…</div>;
  if(!actor)return <Access error={error}/>;
  if(!["director","board"].includes(actor.role))return <Access error="This account has a staff-only view. Use the Staff Phone App; Irene must explicitly authorise Mother Board access."/>;

  return <main className="director-app">
    <aside className="director-sidebar">
      <Link href="/" className="director-brand"><div><img src="/demo/assets/icon-512.png" alt="Approved GA emblem"/><img src="/demo/assets/genevieve-tree-logo-approved-original.jpeg" alt="Approved tree-and-roots mark"/></div><strong>GENEVIEVE App™</strong><small>IRENE CONNECTED HUB</small></Link>
      <nav><button className={view==="overview"?"active":""} onClick={()=>setView("overview")}>⌂ <span>Command Centre</span></button><button className={view==="alerts"?"active":""} onClick={()=>setView("alerts")}>⚑ <span>Safety Alerts</span></button><button className={view==="workload"?"active":""} onClick={()=>setView("workload")}>♡ <span>Workload Protection</span></button><button className={view==="memory"?"active":""} onClick={()=>setView("memory")}>◈ <span>Memory &amp; Learning</span></button><button className={view==="messages"?"active":""} onClick={()=>setView("messages")}>✉ <span>Communications</span>{openMessages>0&&<i>{openMessages}</i>}</button><button className={view==="assign"?"active":""} onClick={()=>setView("assign")}>✓ <span>Assignments</span>{openTasks>0&&<i>{openTasks}</i>}</button><button className={view==="staff"?"active":""} onClick={()=>setView("staff")}>♙ <span>Staff Access</span></button><button className={view==="privacy"?"active":""} onClick={()=>setView("privacy")}>◇ <span>Privacy Mother Board</span></button></nav>
      <div className="sidebar-links"><Link href="/reception?demo=reception">Open Fictional Reception Demo</Link><Link href="/staff?demo=psychologist">Open Fictional Staff Demo</Link><Link href="/demo/index.html">Open Practice Dashboard</Link><a href="/demo/documents/GENEVIEVE_HEALTH_Letter_to_Irene_Program_and_Trial_Guide_V6.pdf" target="_blank" rel="noreferrer">Open Irene’s Trial Guide</a></div>
      <p><b>Fictional data only.</b><br/>No clinical decision-making, diagnosis or automatic external contact.</p>
    </aside>
    <section className="director-main">
      <header className="director-top"><div><span className="eyebrow">Mood &amp; Mind Centre</span><h1>{view==="overview"?"Irene’s Connected Command Centre":label(view)}</h1></div><div className="irene-profile"><span>IR</span><div><b>{actor.displayName}</b><small>Practice Director • Clinical Psychologist</small></div></div></header>
      <div className="director-safety"><b>CONTROLLED DEMONSTRATION</b> Operational communication only. Staff see their own authorised information; Irene and approved Governance Board roles can see the whole-practice communication record.</div>
      <section className="director-content">{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success" onClick={()=>setNotice("")}>{notice}</div>}
        {view==="overview"&&<>
          <section className="director-hero"><div><span className="eyebrow">Two-way mobile connection</span><h2>Irene ↔ authorised staff</h2><p>Messages, assignments, acknowledgements and requests move between Irene’s dashboard and each staff member’s private phone view.</p></div><div className="connection-flow"><span>Irene</span><b>↔</b><span>Role filter</span><b>↔</b><span>Staff app</span></div></section>
          <div className="director-stats"><button onClick={()=>setView("messages")}><b>{openMessages}</b><span>Need acknowledgement</span></button><button onClick={()=>setView("assign")}><b>{openTasks}</b><span>Open assignments</span></button><button onClick={()=>setView("staff")}><b>{activeStaff}</b><span>Authorised staff</span></button><button className={urgent?"danger":""}><b>{urgent}</b><span>Urgent human reviews</span></button></div>
          <div className="director-grid"><Panel title="Recent staff contact" action={<button onClick={()=>setView("messages")}>View all</button>}>{messages.length?<div className="compact-feed">{messages.slice(0,5).map(m=><button key={m.id||""} onClick={()=>{setReplyTo(m.sender_email||"");setView("messages")}}><span className={`priority-dot ${m.priority}`}></span><div><b>{m.subject}</b><small>{m.sender_name} · {label(m.category||"")}</small></div><time>{relative(m.created_at)}</time></button>)}</div>:<Empty text="No staff messages yet."/>}</Panel><Panel title="Assignment responses" action={<button onClick={()=>setView("assign")}>Assign work</button>}>{assignments.length?<div className="compact-feed">{assignments.slice(0,5).map(a=><div key={a.id||""}><span className={`priority-dot ${a.priority}`}></span><div><b>{a.title}</b><small>{a.assigned_to_email} · {label(a.status||"")}</small></div><time>{relative(a.updated_at)}</time></div>)}</div>:<Empty text="No assignments sent yet."/>}</Panel></div>
          <div className="scope-strip"><div><b>Staff receive</b><span>Only their tasks, messages, role modules and support controls</span></div><div><b>Irene receives</b><span>Whole-practice status, responses, escalations and audit evidence</span></div><div><b>Never shared sideways</b><span>Another staff member’s private messages or support requests</span></div></div>
        </>}
        {view==="alerts"&&<DirectorSafety mode="alerts"/>}
        {view==="workload"&&<DirectorSafety mode="workload"/>}
        {view==="memory"&&<MemoryCentre audience="director"/>}
        {view==="messages"&&<div className="director-grid wide-left"><Panel title="Staff communication stream" action={<span>{messages.length} records</span>}>{messages.length?<div className="message-table">{messages.map(m=><article key={m.id||""}><div className="message-meta"><span className={`pill ${m.priority}`}>{label(m.priority||"normal")}</span><b>{m.sender_name}</b><span>→ {m.recipient_email||label(m.recipient_role||"")}</span><time>{new Date(m.created_at||"").toLocaleString("en-AU")}</time></div><h3>{m.subject}</h3><p>{m.body}</p><div className="message-state"><span>{m.read_at?"✓ Read":"○ Unread"}</span><span>{m.acknowledged_at?"✓ Acknowledged":"○ Awaiting acknowledgement"}</span>{m.sender_email!==actor.email&&<button onClick={()=>setReplyTo(m.sender_email||"")}>Reply privately</button>}</div></article>)}</div>:<Empty text="No secure messages yet."/>}</Panel><Panel title={replyTo?"Private reply":"New staff message"}><MessageForm key={replyTo||"new"} onSubmit={send} staff={staff} replyTo={replyTo}/></Panel></div>}
        {view==="assign"&&<div className="director-grid wide-left"><Panel title="Assignment and response board">{assignments.length?<div className="assignment-table"><div className="table-head"><span>Assignment</span><span>Staff</span><span>Status</span><span>Due</span></div>{assignments.map(a=><div key={a.id||""}><span><b>{a.title}</b><small>{a.instructions}</small></span><span>{a.assigned_to_email}</span><span className={`pill ${a.status}`}>{label(a.status||"")}</span><span>{a.due_at?new Date(a.due_at).toLocaleString("en-AU"):"Not set"}</span></div>)}</div>:<Empty text="No assignments yet."/>}</Panel><Panel title="Send an assignment"><AssignmentForm onSubmit={assign} staff={staff}/></Panel></div>}
        {view==="staff"&&<div className="director-grid wide-left"><Panel title="Authorised staff accounts" action={<span>Irene controls access</span>}><div className="staff-table"><div className="table-head"><span>Staff member</span><span>Role</span><span>Access</span><span>Control</span></div>{staff.map(s=><div key={s.email||""}><span><b>{s.display_name}</b><small>{s.email}</small></span><span>{label(s.role||"")}</span><span className={`pill ${s.status}`}>{label(s.status||"")}</span><span>{s.role!=="director"&&<><button onClick={()=>access(s.email||"","paused")}>Pause</button><button onClick={()=>access(s.email||"","revoked")}>Revoke</button></>}</span></div>)}</div></Panel><Panel title="Authorise a staff login"><form className="stack-form" onSubmit={invite}><label>Name<input name="displayName" required maxLength={100} placeholder="Staff member’s name"/></label><label>ChatGPT sign-in email<input name="email" type="email" required placeholder="Exact email used to sign in"/></label><label>Role<select name="role"><option value="psychologist">Psychologist</option><option value="provisional">Provisional Psychologist</option><option value="reception">Reception</option><option value="practice_manager">Practice Manager</option><option value="clinical_lead">Clinical Lead</option><option value="board">Mother Board / Governance Board</option><option value="auditor">Read-only Auditor</option></select></label><button className="gold-button">Authorise access</button><small>Access remains inactive until the exact account signs in. Irene can pause or revoke it.</small></form></Panel></div>}
        {view==="privacy"&&<><section className="director-hero"><div><span className="eyebrow">Irene-controlled access</span><h2>Mother Board &amp; Privacy Control</h2><p>Irene approves who may see whole-practice information. Everyone else receives the minimum necessary information for their role.</p></div></section><div className="permission-matrix"><div className="table-head"><span>Role</span><span>Receives</span><span>Blocked by default</span></div>{[
          ["Irene — Director","Whole-practice operational dashboard, staff access, messages, audit and closure","Therapy content remains outside this operational hub"],
          ["Mother Board / Governance Board","Approved oversight, audit, escalations and director communications","Access until Irene explicitly authorises the account"],
          ["Psychologist","Own appointments, continuity actions, tasks, messages and support","Other staff private messages and unrestricted staff records"],
          ["Provisional Psychologist","Own work, supervision actions, scope, tasks, messages and support","Other clinicians’ work and governance controls"],
          ["Reception","Callbacks, scheduling, approved scripts, transfers and own tasks","Clinical notes, diagnoses, risk judgement and supervision content"],
          ["Practice Manager","Approved staffing and reception operations","Clinical decision-making and therapy content"],
        ].map(row=><div key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><span>{row[2]}</span></div>)}</div><div className="privacy-cards"><div><b>Server-side role checks</b><p>Every message, assignment and roster request is filtered again before data leaves the system.</p></div><div><b>No sideways disclosure</b><p>Staff do not receive another worker’s private support request or direct conversation with Irene.</p></div><div><b>Human control</b><p>No diagnosis, risk score, automatic police/family contact or autonomous clinical action.</p></div><div><b>Audit evidence</b><p>Invites, access changes, messages, acknowledgements and assignment responses are timestamped.</p></div></div></>}
      </section>
      <SafeGuide audience="director" onNavigate={setView}/>
    </section>
  </main>
}

function Panel({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="director-panel"><div className="panel-head"><h2>{title}</h2>{action}</div>{children}</section>}
function Empty({text}:{text:string}){return <div className="empty-state"><span>✓</span><p>{text}</p></div>}
function MessageForm({onSubmit,staff,replyTo}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;staff:Row[];replyTo:string}){return <form className="stack-form" onSubmit={onSubmit}><label>Send privately to<select name="recipientEmail" defaultValue={replyTo}><option value="">Choose staff member…</option>{staff.filter(s=>s.role!=="director").map(s=><option key={s.email||""} value={s.email||""}>{s.display_name} — {label(s.role||"")}</option>)}</select></label><label>Or send to a role<select name="recipientRole"><option value="">Private recipient above</option><option value="all_staff">All authorised staff</option><option value="psychologist">Psychologists</option><option value="provisional">Provisional psychologists</option><option value="reception">Reception</option><option value="practice_manager">Practice managers</option></select></label><label>Category<select name="category"><option value="operational">Operational</option><option value="coverage">Coverage</option><option value="support">Staff support</option><option value="handover">Handover</option><option value="safety">Safety</option></select></label><label>Priority<select name="priority"><option value="normal">Normal</option><option value="amber">Needs attention</option><option value="red">Urgent human review</option></select></label><label>Subject<input name="subject" required maxLength={120}/></label><label>Message<textarea name="body" required maxLength={1200} rows={5} placeholder="Operational information only—no therapy notes or private health information."/></label><button className="gold-button">Send to staff app</button></form>}
function AssignmentForm({onSubmit,staff}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;staff:Row[]}){return <form className="stack-form" onSubmit={onSubmit}><label>Staff member<select name="assignedToEmail" required><option value="">Choose…</option>{staff.filter(s=>s.role!=="director").map(s=><option key={s.email||""} value={s.email||""}>{s.display_name} — {label(s.role||"")}</option>)}</select></label><label>Task<input name="title" required maxLength={120}/></label><label>Instructions<textarea name="instructions" required maxLength={1000} rows={5}/></label><label>Category<select name="category"><option value="operational">Operational</option><option value="coverage">Coverage</option><option value="handover">Handover</option><option value="support">Support</option><option value="safety">Safety</option></select></label><label>Priority<select name="priority"><option value="normal">Normal</option><option value="amber">Needs attention</option><option value="red">Urgent human review</option></select></label><label>Due<input name="dueAt" type="datetime-local"/></label><button className="gold-button">Send assignment</button></form>}
function Access({error}:{error:string}){return <main className="access-screen"><img src="/demo/assets/icon-512.png" alt="GENEVIEVE App"/><h1>Irene’s connected dashboard</h1><p>{error}</p><a className="gold-button" href="/signin-with-chatgpt?return_to=/irene">Sign in with ChatGPT</a><small>The first authorised sign-in securely claims Irene’s director account.</small></main>}
function relative(value:string|null){if(!value)return"";const mins=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));return mins<1?"now":mins<60?`${mins}m`:mins<1440?`${Math.floor(mins/60)}h`:`${Math.floor(mins/1440)}d`}
